version: '1.0'
stages:
  - build_func_test
  - func_test
  - build_e2e_test
  - e2e_test
  - push_release_image
  - update_service

steps:
  BuildFuncTestEnvironment:
    title: Build Func Test Environment
    type: build
    image_name: mcbhenwood/a2siservicesapi-functest
    working_directory: ./services
    dockerfile: Dockerfile.ci
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    stage: build_func_test

  BuildLinterDockerImage:
    title: Build Linter Docker Image
    type: build
    image_name: mcbhenwood/pycodestyle
    working_directory: ./pycodestyle
    dockerfile: Dockerfile
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    stage: build_func_test

  LintCodebase:
    title: Lint the Django codebase
    image: '${{BuildLinterDockerImage}}'
    commands:
      - pycodestyle ./services
    stage: func_test

  RunDjangoTest:
    title: "Run the Django functional tests"
    image: '${{BuildFuncTestEnvironment}}'
    commands:
      - /code/manage.py test /code
    environment:
      - "DJANGO_PAGE_TITLE=A2SI Services API (prototype) - Func Tests"
      - DJANGO_SECRET_KEY=NotReallyASecret
    stage: func_test

  BuildProd:
    title: Build Prod Environment (release candidate)
    type: build
    image_name: mcbhenwood/a2siservicesapi
    working_directory: ./services
    dockerfile: Dockerfile.prod
    tag: latest
    stage: build_e2e_test

  BuildE2ETestAPI:
    title: Build the API End-to-End tests
    type: build
    image_name: mcbhenwood/a2siservicesapi-e2etest-api
    working_directory: ./e2e-test-api
    dockerfile: Dockerfile.ci
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    stage: build_e2e_test

  BuildE2ETestUI:
    title: Build the UI End-to-End tests
    type: build
    image_name: mcbhenwood/a2siservicesapi-e2etest-ui
    working_directory: ./e2e-test-ui
    dockerfile: Dockerfile.ci
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    stage: build_e2e_test

  RunE2ETestAPI:
    title: "Run the API End-to-End tests"
    type: composition
    working_directory: ./
    composition:
      version: '3'
      services:
        api:
          image: '${{BuildProd}}'
          environment:
            DJANGO_DB_HOST: "defaultdb"
            DJANGO_DB_PORT: "5432"
            DJANGO_DB_NAME: "ci"
            DJANGO_DB_USER: "django"
            DJANGO_DB_PASSWORD: "password"
            DJANGO_HOSTNAME: "api"
            DJANGO_SECRET_KEY: "ThisIsNotReallyASecret"
          ports:
            - 8000
          depends_on:
            - defaultdb
        defaultdb:
          image: "postgres:11.2-alpine"
          environment:
            POSTGRES_DB: "ci"
            POSTGRES_USER: "django"
            POSTGRES_PASSWORD: "password"
    composition_candidates:
      e2etest:
        image: '${{BuildE2ETestAPI}}'
        environment:
          API_HOST: "api"
          API_PORT: "8000"
          API_SCHEME: "http"
        links:
          - api
    stage: e2e_test

  RunE2ETestUI:
    title: "Run the UI End-to-End tests"
    type: composition
    working_directory: ./
    composition:
      version: '3'
      services:
        api:
          image: '${{BuildProd}}'
          environment:
            DJANGO_DB_HOST: "defaultdb"
            DJANGO_DB_PORT: "5432"
            DJANGO_DB_NAME: "ci"
            DJANGO_DB_USER: "django"
            DJANGO_DB_PASSWORD: "password"
            DJANGO_HOSTNAME: "api"
            DJANGO_PAGE_TITLE: "A2SI Services API (prototype) - E2E UI Tests"
            DJANGO_SECRET_KEY: "ThisIsNotReallyASecret"
          ports:
            - 8000
          depends_on:
            - defaultdb
        defaultdb:
          image: "postgres:11.2-alpine"
          environment:
            POSTGRES_DB: "ci"
            POSTGRES_USER: "django"
            POSTGRES_PASSWORD: "password"
    composition_candidates:
      e2etest:
        image: '${{BuildE2ETestUI}}'
        environment:
          API_HOST: "api"
          API_PORT: "8000"
          API_SCHEME: "http"
        links:
          - api
    stage: e2e_test

  PushReleaseImage:
    type: push
    title: "[MASTER] Push new service release to Docker Hub"
    candidate: '${{BuildProd}}'
    image_name: 'mcbhenwood/a2si-services-api'
    registry: dockerhub
    tag: latest
    stage: push_release_image
    when:
      branch:
        only:
          - master

  PushStaticAssets:
    title: "[MASTER] Push static assets to S3"
    image: '${{BuildFuncTestEnvironment}}'
    commands:
      - ./services/manage.py collectstatic --noinput
    environment:
      - AWS_ACCESS_KEY_ID=${{DEPLOY_AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{DEPLOY_AWS_SECRET_ACCESS_KEY}}
      - AWS_S3_REGION_NAME=eu-west-2
      - AWS_STORAGE_BUCKET_NAME=static.a2sisap.mcbhenwood.com
      - DJANGO_SECRET_KEY=NotReallyASecret
    stage: update_service
    when:
      branch:
        only:
          - master

  UpdateServiceImage:
    title: "[MASTER] Update ECS service with new Docker Hub image"
    image: codefresh/cf-deploy-ecs
    commands:
      - cfecs-update --image-name mcbhenwood/a2si-services-api --image-tag latest eu-west-2 ProdRealAPI ProdRealAPI
    environment:
      - AWS_ACCESS_KEY_ID=${{DEPLOY_AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{DEPLOY_AWS_SECRET_ACCESS_KEY}}
    stage: update_service
    when:
      branch:
        only:
          - master
