version: '1.0'
stages:
  - build
  - unit_test

steps:
  BuildAPIDockerImage:
    title: Build API Docker Image
    type: build
    image_name: mcbhenwood/a2siservicesapi
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    stage: build

  BuildLinterDockerImage:
    title: Build Linter Docker Image
    type: build
    image_name: mcbhenwood/pycodestyle
    working_directory: ./pycodestyle
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    stage: build

  LintCodebase:
    title: Lint the Django codebase
    image: '${{BuildLinterDockerImage}}'
    commands:
      - pycodestyle ./services
    stage: unit_test

  RunDjangoTests:
    title: "Run the Django unit & functional tests"
    image: '${{BuildAPIDockerImage}}'
    commands:
      - ./services/manage.py test ./services
    environment:
      - DJANGO_SECRET_KEY=NotReallyASecret
    stage: unit_test
