FROM python:3.5-alpine
ENV PYTHONUNBUFFERED 1
WORKDIR /code
COPY services/requirements /code/requirements
RUN pip install -r requirements/base.txt -r requirements/prod.txt
WORKDIR /code/services
COPY services/api /code/services/api
COPY services/services /code/services/services
EXPOSE 8000
ENTRYPOINT ["gunicorn"]
CMD ["-b", "0.0.0.0:8000", "services.wsgi:application"]
