FROM python:3.5-alpine
ENV PYTHONUNBUFFERED 1
RUN apk update && apk upgrade && \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip install --upgrade pip
COPY container-scripts /scripts
COPY requirements /code/requirements
RUN pip install -r /code/requirements/base.txt -r /code/requirements/dev.txt && \
    apk --purge del .build-deps
EXPOSE 8000
ENTRYPOINT ["/scripts/migrate-then-start.sh"]

