FROM python:3.5-alpine
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
COPY requirements /code/requirements
RUN pip install -r /code/requirements/base.txt -r /code/requirements/prod.txt
COPY . /code/
WORKDIR /code
EXPOSE 8000
ENTRYPOINT ["gunicorn"]
CMD ["-b", "0.0.0.0:8000", "services.wsgi:application"]
