version: '3.7'
services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    environment:
      DJANGO_HOSTNAME: "api"
      DJANGO_SECRET_KEY: "ThisIsNotReallyASecret"
    ports:
      - "8000:8000"
    volumes:
      - "..:/code"

  e2etest:
    build: .
    environment:
      API_HOST: "api"
      API_PORT: "8000"
    volumes:
      - ".:/test"
    depends_on:
      - api
